/*
 * Example of REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * MainUser
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-05T14:05:31.445+05:00")
public class MainUser {
  @SerializedName("normalName")
  private String normalName = null;

  public MainUser normalName(String normalName) {
    this.normalName = normalName;
    return this;
  }

   /**
   * Get normalName
   * @return normalName
  **/
  @ApiModelProperty(value = "")
  public String getNormalName() {
    return normalName;
  }

  public void setNormalName(String normalName) {
    this.normalName = normalName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MainUser mainUser = (MainUser) o;
    return Objects.equals(this.normalName, mainUser.normalName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(normalName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MainUser {\n");
    
    sb.append("    normalName: ").append(toIndentedString(normalName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

