spring:
  redis:
    #password: qwertyA
    sentinel:
      master: mymaster
      nodes: localhost:26379
      password: qwertyB

redis:
  topic:
    logout: logout-topic
    purchase: purchase-topic
