CREATE TABLE AUTHOR (
  ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50)
);

CREATE TABLE BOOK (
  ID INT PRIMARY KEY,
  TITLE VARCHAR(100),
  AUTHOR_ID INT,
  CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);
