/*
 * Example of REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.User;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * API tests for SameNameBApi
 */
public class SameNameBApiTest {

    private final SameNameBApi api = new SameNameBApi();

    
    /**
     * getUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserUsingGET1Test() throws ApiException {
        User response = api.getUserUsingGET1();
        assertEquals("NYC, ST John street 23", response.getAddress());
        // TODO: test validations
    }
    
}
