/*
 * Example of REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.MainUser;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * API tests for SameNameAApi
 */
public class SameNameAApiTest {

    private final SameNameAApi api = new SameNameAApi();

    
    /**
     * getUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserUsingGETTest() throws ApiException {
        MainUser response = api.getUserUsingGET();
        assertEquals("John", response.getNormalName());
        // TODO: test validations
    }
    
}
