/*
 * This file was automatically generated by EvoSuite
 * Sat May 30 09:49:00 GMT 2020
 */

package com.github.hofls.javatests.evosuite.product;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

public class ProductsService_ESTest  {

  @Test
  public void test0()  throws Throwable  {
      ProductsService productsService0 = new ProductsService((ProductsRepository) null);
      // Undeclared exception!
      try { 
        productsService0.calculateProducts((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test1()  throws Throwable  {
      ProductsRepository productsRepository0 = new ProductsRepository();
      ProductsService productsService0 = new ProductsService(productsRepository0);
      String string0 = productsService0.calculateProducts((Long) null);
      assertEquals("Nothing", string0);
  }
}
