INSERT INTO CAMPUS(ID, NAME) VALUES(569, 'St Peters 234');
INSERT INTO STUDENT(ID, NAME, CAMPUS_ID) VALUES(234, 'Helga', 569);

INSERT INTO CAMPUS(ID, NAME) VALUES(984, 'Evil Peters 542');
INSERT INTO STUDENT(ID, NAME, CAMPUS_ID) VALUES(546, 'Wander', 984);
